let EventType = {
    /**
     * 发送的data格式{seatId:,pokers:[]}
     * 接收的data格式{cmd:"",playerId:socket.id,pokers:[]}
     */

    MSG_DDZ_PLAYER_CONNECTED: "MSG_DDZ_PLAYER_CONNECTED",
    MSG_DDZ_ENTER_TABLE: "MSG_DDZ_ENTER_TABLE",
    MSG_DDZ_ALL_TABLES: "MSG_DDZ_ALL_TABLES",
    MSG_DDZ_PASS: "MSG_DDZ_PASS",
    MSG_DDZ_ALL_PLAYERS: "MSG_DDZ_ALL_PLAYERS",
    MSG_DDZ_DEAL_POKER: "MSG_DDZ_DEAL_POKER",
    MSG_DDZ_DISCARD: "MSG_DDZ_DISCARD",
    MSG_DDZ_CREATE_ROOM: "MSG_DDZ_CREATE_ROOM",
    MSG_DDZ_PLAY_POKER: "MSG_DDZ_PLAY_POKER",
    MSG_DDZ_START_GAME: "MSG_DDZ_START_GAME",
    MSG_DDZ_GAME_OVER: "MSG_DDZ_GAME_OVER",

};
module.exports = EventType;